server:
  port: 8000
#  ssl:
#    key-store:
#    key-store-password:
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

#    url: jdbc:mysql://mark1.dashwood.xyz:3306/haetae?serverTimezone=Asia/Shanghai&useSSL=false&characterEncoding=utf8
    url: jdbc:mysql://192.168.3.30:3306/haetae?serverTimezone=Asia/Shanghai&useSSL=false&characterEncoding=utf8
    username: root
    password: dashwood
#    password: reUgWvUxwjkk
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  banner:
    location: config/banner.txt
  jackson:
    serialization:
      write-dates-as-timestamps: true

logging:
  config: classpath:config/logback.xml
wechat:
  appId:
  secret:
