server:
  port: 8000
#  ssl:
#    key-store:
#    key-store-password:
spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/haetae?serverTimezone=Asia/Shanghai&useSSL=false&characterEncoding=utf8
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  banner:
    location: config/banner.txt
  jackson:
    serialization:
      write-dates-as-timestamps: true

logging:
  config: classpath:config/logback.xml
wechat:
  appId:
  secret:
